global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['gracious_wilson:8080']

  - job_name: 'backend'
    metrics_path: /tpfoyer/actuator/prometheus
    static_configs:
      - targets: ['backend:8089']
