version: '3.8'

services:
  backend:
    image: mouadhs/reservation_management:latest
    restart: on-failure
    networks:
      - jenkins-sonarqube-network
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
    ports:
      - "8089:8089"
    depends_on:
      - db

  db:
    image: mysql:8.0
    networks:
      - jenkins-sonarqube-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - /var/jenkins_home/workspace/MouadhSaadaoui5Arctic7/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - jenkins-sonarqube-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - jenkins-sonarqube-network

networks:
  jenkins-sonarqube-network:

volumes:
  mysql_data:
