version: '3.8'

services:
  backend:
    image: mouadhs/reservation_management:latest
    restart: on-failure
    networks:
      - jenkins-sonarqube-network
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "root",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true
    ports:
      - "8089:8089"
    depends_on:
      - db

  db:
    image: mysql:8.0
    networks:
      - jenkins-sonarqube-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  jenkins-sonarqube-network:
    external: true

volumes:
  mysql_data:
